### ISSUE TITLE
bash: action-entrypoint: No such file or directory

### ISSUE THREAD

**Issue by jeremy-bepoix** [python-semantic-release/upload-to-gh-release#6]
Hi, 
Since latest release i'v got an error on github action. Working fine yesterday May 23, 2024 12:09 PM GMT+2

`bash: action-entrypoint: No such file or directory`.
![image](https://github.com/python-semantic-release/upload-to-gh-release/assets/145460090/5a6dc5eb-12d8-4a46-abb5-04ee45f0ee73)

Github action is set like documentation : 
https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html

**Comment by codejedi365** [comment]
Thank you for the report, yes, I made a bunch of changes yesterday. Maintaining PATH variables are so annoying in Docker unfortunately.

I'll have it fixed asap. Once you hear back from me, I recommended you lock in the version (rather than point at main) now that I have created release tags per version.

**Comment by codejedi365** [comment]
@jeremy-bepoix, would you try out the replaced version `v8.7.0` (which uses the same PSR version as yesterday). Then if that works and you desire to upgrade, I released `v9.0.2` as well.  I hope to get a verification from you first before I re-release all the versions in between `9.0.2` and `9.7.3` as I had done yesterday.  I wiped them all out since they would all be broken as they have the same problem described in your issue report.

**Comment by afuetterer** [comment]
Hi there,
I succesfully created a release today and the GHA v9.0.2 uploaded the assets: https://github.com/afuetterer/python-re3data/actions/runs/9244887611/job/25430718880

**Comment by codejedi365** [comment]
Awesome! Thanks a bunch, I'll bump all the following versions then

**Comment by codejedi365** [comment]
Versions v9.0.2 through v9.7.3 have been released. In line with @afuetterer's comment, this ticket should be resolved. Let me know if this fails to resolve your issue.
